# Generated by Django 3.2.4 on 2021-06-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
